# This file configures the analyzer to use the lint rule set from `package:flutter_lints`
# This is the recommended approach for new projects.
# The core lints can be enabled by adding `package:flutter_lints` to the
# `dev_dependencies` section of your `pubspec.yaml` file and then running
# `dart pub get`.

include: package:flutter_lints/flutter.yaml

# For more information about the core and recommended set of lints, see
# https://dart.dev/go/core-lints

# Uncomment the following section to specify additional rules:
# linter:
#   rules:
#     - camel_case_types
#     - library_names
#     - directives_ordering
#     - avoid_empty_else
#     - prefer_const_constructors
#     - prefer_final_fields
#     - prefer_is_empty
#     - prefer_is_not_empty
#     - prefer_typing_uninitialized_variables
#     - slash_for_doc_comments
#     - type_init_formals
#     - unawaited_futures
#     - unnecessary_brace_in_string_interps
#     - unnecessary_getters_setters
#     - unnecessary_new
#     - unnecessary_null_aware_assignments
#     - unnecessary_statements
#     - unrelated_type_equality_checks
#     - use_rethrow_when_possible
#     - valid_regexps 