workflows:
  ios-workflow-id:
    name: iOS Sample Workflow
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: Codemagic
    environment:
      vars:
        BUNDLE_ID: "com.personalcoach.padel"
        XCODE_WORKSPACE: "PersonalPadelCoach.xcworkspace" # <-- Name of your Xcode workspace
        XCODE_SCHEME: "PersonalPadelCoach" # <-- Name of your Xcode scheme
    scripts:
      - name: Build ipa for distribution
        script: | 
          xcode-project build-ipa \
          --workspace "$CM_BUILD_DIR/ios/$XCODE_WORKSPACE" \
          --scheme "$XCODE_SCHEME"
    artifacts:
        - build/ios/ipa/*.ipa
    code_signing:
      xcode: automatic
      distribution_type: development