# Check out https://docs.codemagic.io/yaml/building-a-react-native-app/ for more information
# Please review and update values

# The workflow name. You can have multiple workflows for different purposes.
workflows:
  rn-ios-test-build:
    # A human-readable name for the workflow.
    name: "React Native iOS Test Build and Distribute"
    
    # Specify the instance type for the build. Mac mini M1 is a good default.
    instance_type: mac_mini_m2
    
    # Define the build environment. This includes Node, npm, and Xcode versions.
    environment:
      
      # Use the latest stable Xcode and a supported Node.js version.
      xcode: latest
      node: 18.x
      npm: 9.x
      
      # Set up your App Store Connect API key variables. These must be
      # configured in the Codemagic UI settings for secure storage.
      vars:
        APP_STORE_CONNECT_KEY_ID: Encrypted
        APP_STORE_CONNECT_ISSUER_ID: Encrypted
        APP_STORE_CONNECT_PRIVATE_KEY: Encrypted
        
    # The sequence of commands to execute.
    scripts:
      # Use a simple script to install the Node.js dependencies for the project.
      - name: Install Node dependencies
        script: |
          npm install
          
      # Navigate to the 'ios' directory and install the CocoaPods dependencies.
      - name: Pod install
        script: |
          cd ios
          pod install
          
      # A script to build the iOS application archive using xcodebuild.
      - name: Build iOS app
        script: |
          # The -workspace and -scheme should match your project's .xcworkspace and scheme name.
          # The --no-codesign flag tells Codemagic to handle the signing process with the App Store Connect API key.
          xcodebuild -workspace ios/YourApp.xcworkspace -scheme YourApp -configuration Release -sdk iphoneos -archivePath build/YourApp.xcarchive clean archive
          
    # Define the build artifacts to save and publish.
    artifacts:
      - build/ios/ipa/*.ipa

    # Configure the publishing settings.
    publishing:
      app_store_connect:
        # Enable the publishing to App Store Connect.
        enabled: true
        
        # This tells Codemagic to use the variables defined in the environment
        # for authentication.
        api_key:
          key_id: $APP_STORE_CONNECT_KEY_ID
          issuer_id: $APP_STORE_CONNECT_ISSUER_ID
          private_key: $APP_STORE_CONNECT_PRIVATE_KEY
          
        # Set to true to automatically manage provisioning profiles and certificates.
        provisioning_profiles: automatic
        
        # Configure the distribution to TestFlight.
        testflight:
          # Enable TestFlight distribution.
          enabled: true
          
          # The name of the TestFlight group you want to distribute to.
          # You must create this group in App Store Connect.
          group: "Codemagic Testers"

          # Configuration related to App Store (optional)
          # Note: This action is performed during post-processing.
          submit_to_app_store: false