workflows:
  ios-workflow-id:
    name: iOS Sample Workflow
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: Codemagic
    environment:
      groups:
        - Store
      vars:
        BUNDLE_ID: "com.personalcoach.padel"
        XCODE_WORKSPACE: "PersonalPadelCoach.xcworkspace" # <-- Name of your Xcode workspace
        XCODE_SCHEME: "PersonalPadelCoach" # <-- Name of your Xcode scheme
    scripts:
      - name: Install npm dependencies
        script: |
          npm install
      - name: Clear CocoaPods dependencies
        script: |
          cd ios && pod cache clean boost
      - name: Install boost
        script: |
          cp boost.podspec node_modules/react-native/third-party-podspecs/boost.podspec
      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install
      - name: Set up code signing identities
        script: |
          app-store-connect fetch-signing-files com.personalcoach.padel --create --type IOS_APP_DEVELOPMENT --platform IOS --issuer-id cfa20d66-4afd-4922-85f7-9fbacefc7b21 --key-id 5KMXA4J2W3 --private-key @AUTH_KEY --certificate-key @CERTIFICATE_KEY
      - name: Build ipa for distribution
        script: | 
          xcode-project build-ipa \
          --workspace "$CM_BUILD_DIR/ios/$XCODE_WORKSPACE" \
          --scheme "$XCODE_SCHEME"    
    artifacts:
        - build/ios/ipa/*.ipa